#!/usr/bin/bash

source /etc/os-release

# change here if you want to fake your distro (?)
# NAME="Distro Name"

case $NAME in
    "Arch Linux") 
    color=39
    packages="Packages: $(tput sgr0)$(pacman -Qqe | wc -l), $(pacman -Qq | wc -l) total$(tput setaf "$color")"
    ;;
    "Artix Linux")
    color=6
    packages="Packages: $(tput sgr0)$(pacman -Qqe | wc -l), $(pacman -Qq | wc -l) total$(tput setaf "$color")"
    ;;
    "Debian GNU/Linux") 
    color=1
    packages="Packages: $(tput sgr0)$(dpkg-query -l | grep ^ii | awk '{print $2}' | wc -l)$(tput setaf 1)"
    ;;
    "Void") 
    color=42
    packages="Packages: $(tput sgr0)$(xbps-query -m | wc -l), $(xbps-query -l | wc -l) total$(tput setaf $color)"
    ;;
    "NixOS") 
    color=7
    packages="Packages: $(tput sgr0)$(nix-env -q | wc -l), $(nix-store --query --requisites /run/current-system/ | sort -u | wc -l) total$(tput setaf $color)"
    ;;
esac

get_gpu () {
     lspci | grep -i 'VGA' | awk -F': ' '{print $2}' | sed 's/(rev ..)//g' | head -n1 | sed -n 's/.*\[\(.*\)\].*/\1/p'
}

get_shell () {
    parent_process=$(ps -o comm= -p $(ps -o ppid= -p $$))
    case "$parent_process" in
        "bash") echo "bash, Bourne Again Shell";;
        "dash")echo "dash, Almquist Shell";;
        "zsh") echo "zsh, Z shell";;
        "tcsh") echo "tcsh, TENEX C shell";;
        "csh") echo "csh, C shell";;
        "ksh") echo "ksh, Korn shell";;
        "fish")echo "fish";;
        *)echo "$parent_process";;
    esac
}

hostname="Hostname: $(tput sgr0)$(cat /sys/class/dmi/id/product_name | awk '{print $1" "$2}')$(tput setaf $color)"
os_release="Release: $(tput sgr0)$PRETTY_NAME$(tput setaf $color)"
kernel="Kernel: $(tput sgr0)$(uname -r)$(tput setaf $color)"
uptime="Uptime: $(tput sgr0)$(uptime -p | sed 's/up //g')$(tput setaf $color)"
shell="Shell: $(tput sgr0)$(get_shell)$(tput setaf $color)"
term="Term: $(tput sgr0)$(echo $TERM)$(tput setaf $color)"
disk="Disk: $(tput sgr0)$(echo $(df -h | awk '/\/$/ {print $3 "/" $2 " (" $5 ")" }'))$(tput setaf $color)"
ram="RAM: $(tput sgr0)$(free --mega | awk '/^Mem:/ {print $3 "MB" "/" $2 "MB (" int(100*$3/$2) "%)" }') "$(tput setaf $color)""
cpu="CPU: $(tput sgr0)$(echo $(grep -m1 'model name' /proc/cpuinfo | awk -F': ' '{print $2}' | sed 's/with.*$//'))$(tput setaf $color)"
gpu="GPU: $(tput sgr0)$(get_gpu)$(tput setaf $color)"
# battery="Battery: $(tput sgr0)$(acpi -b)$(tput setaf $color)"
# wm="WM: $(tput sgr0)$(xprop -id $(xprop -root -notype | awk '$1=="_NET_SUPPORTING_WM_CHECK:"{print $5}') -notype -f _NET_WM_NAME 8t | grep "WM_NAME" | cut -f2 -d \")$(tput setaf $color)"

element=(
  "$hostname"
  "$os_release"
  "$packages"
  "$kernel"
  "$uptime"
  "$shell"
  "$term"
  "$disk"
  "$ram"
  "$cpu"
  "$gpu"
  ""
  "$(for c in $(seq 1 6); do tput setaf $c; echo -n "██"; done; tput sgr0; echo)$(tput setaf $color)"
)

display_cpu=true
display_gpu=true
display_disk=true
display_ram=true

remove() {
    new_array=()
    for item in "${element[@]}"; do
        if [[ "$item" != "$1" ]]; then
            new_array+=("$item")
        fi
    done
    element=("${new_array[@]}")
}

help() {
    echo "help: you can chose elements to not display:
-c: no cpu
-g: no gpu
-d: no disk
-r: no ram
-s: no shell
-p: no packages
-k: no kernel
-t: no term
-w: no wm"
}

while [[ $# -gt 0 ]]; do
    case "$1" in
       -*)
            arg="${1#-}"
            for ((i = 0; i < ${#arg}; i++)); do
                case "${arg:$i:1}" in
                    v | V) echo "1.8.2"; exit 0;;
                    o) remove "$os_release"; shift;;
                    h) remove "$hostname"; shift;;
                    t) remove "$term"; shift;;
                    k) remove "$kernel"; shift;;
                    p) remove "$packages"; shift;;
                    s) remove "$shell"; shift;;
                    c) remove "$cpu"; shift;;
                    g) remove "$gpu"; shift;;
                    d) remove "$disk"; shift;;
                    r) remove "$ram"; shift;;
                    w) remove "$wm"; shift;;
                    h) help; exit 0;;
                esac
            done
            shift
            ;;
        *)
            echo "unknown option '$1'"
            help
            exit 1
            ;;
    esac
done

test -z "$(get_gpu)" && remove "$gpu"

how_many_lines=$(echo $(whoami)$(cat /proc/sys/kernel/hostname) | wc -c)
case $NAME in
    "Arch Linux")
echo -e "$(tput setaf $color)            
              +                $(tput bold)$(tput setaf $color)$(whoami)$(tput sgr0)@$(tput sgr0)$(cat /proc/sys/kernel/hostname)$(tput setaf $color) 
             +++               $(tput sgr0)$(for ((i=0; i<how_many_lines+1; i++)); do printf "%s" "―"; done)$(tput setaf $color)
            +++++              ${element[0]}
           +++++++             ${element[1]}
           ++++++++            ${element[2]}
         ++ ++++++++           ${element[3]}
        +++++++++++++          ${element[4]}
       +++++++++++++++         ${element[5]}
      +++++++++++++++++        ${element[6]}
     ++++++++   ++++++ +       ${element[7]}
    ++++++++     +++++++       ${element[8]}
   +++++++++     +++++++++     ${element[9]} 
  ++++                 ++++    ${element[10]} 
 ++                       ++   ${element[11]} 
+                           +  ${element[12]} 
$(tput sgr0)";;

    "Artix Linux")
echo -e "$(tput setaf $color)            
              x                $(tput bold)$(tput setaf $color)$(whoami)$(tput sgr0)@$(tput sgr0)$(cat /proc/sys/kernel/hostname)$(tput setaf $color)
             xxx               $(tput sgr0)$(for ((i=0; i<how_many_lines+1; i++)); do printf "%s" "―"; done)$(tput setaf $color)
            xxxxx              ${element[0]}
           xxxxxxx             ${element[1]}
          xxxxxxxxx            ${element[2]}
            xxxxxxxx           ${element[3]}
        x      xxxxxx          ${element[4]}
       xxxxxxx     xxx         ${element[5]}
      xxxxxxxxxxxx    +        ${element[6]}
     xxxxxxxxxxxxxxxxxx        ${element[7]}
    xxxxxxxxxxxxxx     xx      ${element[8]}
   xxxxxxxxxx      xxxxxxx     ${element[9]} 
  xxxxxx           xxxxxxxx    ${element[10]} 
 xxx                     xxx   ${element[11]}
xx                         xx  ${element[12]}
$(tput sgr0)";;

    "Debian GNU/Linux") 
echo -e "$(tput setaf 1)
          #######          $(tput bold)$(tput setaf 1)$(whoami)$(tput sgr0)@$(tput sgr0)$(cat /proc/sys/kernel/hostname)$(tput setaf 1)            
      ################     $(tput sgr0)$(for ((i=0; i<how_many_lines+1; i++)); do printf "%s" "―"; done)$(tput setaf 1)             
    #####           ####   ${element[0]}             
   ###                ###  ${element[1]}             
  ##          ###     ###  ${element[2]}             
 ###        ##    #    ##  ${element[3]}             
 ##        #       #   ##  ${element[4]}             
 ##       ##          ##   ${element[5]}             
 ##        #     #    #    ${element[6]}             
 ##         ##      ##     ${element[7]}             
  ##          ####         ${element[8]}             
   ##                      ${element[9]}             
    ##                     ${element[10]}             
     ##                    ${element[11]}             
       ###                 ${element[12]}              
          ##             
$(tput sgr0)";;

    "Void")
echo -e "
          $(tput setaf $color)++++++++++          $(tput bold)$(tput setaf $color)$(whoami)$(tput sgr0)@$(tput sgr0)$(cat /proc/sys/kernel/hostname)$(tput setaf $color)
        +++++++++++++++       $(tput sgr0)$(for ((i=0; i<how_many_lines+1; i++)); do printf "%s" "―"; done)$(tput setaf $color)
         +++      +++++++     ${element[0]}  
    ##               +++++    ${element[1]} 
   #####              +++++   ${element[2]} 
  #####     ++++++     +++++  ${element[3]} 
  ####     ++++++++     ++++  ${element[4]} 
  ####     ++++++++     ++++  ${element[5]} 
  #####     ++++++     +++++  ${element[6]} 
   #####              +++++   ${element[7]} 
    #####               ++    ${element[8]} 
     #######      ###         ${element[9]} 
       ###############        ${element[10]}
          ##########          ${element[11]}
                              ${element[12]}
$(tput sgr0)";; 

    "NixOS")
echo -e "
       [1;34m*[0m[1;34m*[0m[1;34m*[0m     ****   ***       \e[1m\e[38;5;39m$(whoami)\e[0m@\e[38;5;39m$(cat /proc/sys/kernel/hostname)\e[0m
        [1;34m*[0m[1;34m*[0m[1;34m*[0m[1;34m*[0m    ********        \e[0m$(for ((i=0; i<how_many_lines+1; i++)); do printf "%s" "―"; done)\e[38;5;39m
         [1;34m*[0m[1;34m*[0m[1;34m*[0m[1;34m*[0m    ******         ${element[0]}
    [1;34m*[0m[1;34m*[0m[1;34m*[0m[1;34m*[0m[1;34m*[0m[1;34m*[0m[1;34m*[0m[1;34m*[0m[1;34m*[0m[1;34m*[0m[1;34m*[0m[1;34m*[0m[1;34m*[0m[1;34m*[0m****    [1;34m*[0m[1;34m*[0m    ${element[1]} 
         ***        ***  [1;34m*[0m[1;34m*[0m[1;34m*[0m[1;34m*[0m   ${element[2]} 
        ***          ***[1;34m*[0m[1;34m*[0m[1;34m*[0m[1;34m*[0m    ${element[3]} 
 *********            *[1;34m*[0m[1;34m*[0m[1;34m*[0m[1;34m*[0m[1;34m*[0m[1;34m*[0m[1;34m*[0m[1;34m*[0m ${element[4]} 
 ********[1;34m*[0m            [1;34m*[0m[1;34m*[0m[1;34m*[0m[1;34m*[0m[1;34m*[0m[1;34m*[0m[1;34m*[0m[1;34m*[0m[1;34m*[0m ${element[5]} 
    ****[1;34m*[0m[1;34m*[0m[1;34m*[0m          [1;34m*[0m[1;34m*[0m[1;34m*[0m        ${element[6]} 
   ****  [1;34m*[0m[1;34m*[0m[1;34m*[0m        [1;34m*[0m[1;34m*[0m[1;34m*[0m         ${element[7]} 
    **    [1;34m*[0m[1;34m*[0m[1;34m*[0m[1;34m*[0m**************    ${element[8]} 
         [1;34m*[0m[1;34m*[0m[1;34m*[0m[1;34m*[0m[1;34m*[0m[1;34m*[0m    ****         ${element[9]} 
        [1;34m*[0m[1;34m*[0m[1;34m*[0m[1;34m*[0m[1;34m*[0m[1;34m*[0m[1;34m*[0m[1;34m*[0m    ****        ${element[10]} 
       [1;34m*[0m[1;34m*[0m[1;34m*[0m   [1;34m*[0m[1;34m*[0m[1;34m*[0m[1;34m*[0m     ***       ${element[11]}
                                ${element[12]}
       "

esac








#      _                 _       __      _       _
#  ___(_)_ __ ___  _ __ | | ___ / _| ___| |_ ___| |__
# / __| | '_ ` _ \| '_ \| |/ _ | |_ / _ | __/ __| '_ \
# \__ | | | | | | | |_) | |  __|  _|  __| || (__| | | |
# |___|_|_| |_| |_| .__/|_|\___|_|  \___|\__\___|_| |_|
#                 |_|
#
#  CC BY-NC-SA 4.0 Deed 
#  simplefetch, a work by clyde
#
     
#
#  simplefetch / sfetch / sf 1.8.2
#  created by clyde, on 18 feb 2024 at 16:$color CET
#
#                     lol, 39 got replaced by $color

    # clyde, on 3 mar 2024 at 15:33 CET 
    # 1.0.2 patch notes: added the "Disk" line

    # clyde, on 12 mar 2024 at 08:33 CET
    # 1.0.3 patch notes: made the code cleaner with variables

    # clyde, on 25 mar 2024 23:49 CET
    # 1.1 patch notes: created more extensibility with $_1, $_2, etc.

    # clyde, on 3 apr 2024 09:03 CEST (time change)
    # 1.1.1 patch notes: added colors at the bottom

    # clyde, on 5 apr 2024 17:36 CEST 
    # 1.2 patch notes: added options to ignore elements
    # 1.2.1 patch notes: cleaned the code and removed long options like --no-cpu

    # clyde, on 12 may 2024 02:03 CEST 
    # 1.3 patch notes: added debian support!

    # clyde, on 23 may 2024 23:11 CEST 
    # 1.4 patch notes: changed the logo to a MUCH cooler one!

    # clyde, on 26 may 2024 17:49 CEST 
    # 1.5 patch notes: changed debian logo, add uptime, etc.

    # clyde, on 03 jun 2024 11:09 CEST 
    # 1.6 patch notes: created support for Void

    # clyde, on 04 jun 2024 03:37 CEST 
    # 1.7 patch notes: created support for NixOS

    # clyde, on 09 jun 2024 15:26 CEST 
    # 1.7.1 patch notes: improved shell variable, adding get_shell()

    # clyde, on 11 jun 2024 14:25 CEST 
    # 1.8 patch notes: add Artix support and os_release and hostname variable

    # clyde, on 13 jun 2024 15:07 CEST 
    # 1.8.1 patch notes: make Arch logo bigger

    # clyde, on 13 jun 2024 15:07 CEST 
    # 1.8.2 patch notes: add percentages in Disk and RAM, and put the / together

